Improve argument validation in scripts and added more scripts

diff --git a/docker/db-scripts/import_schema b/docker/db-scripts/import_schema
--- a/docker/db-scripts/import_schema
+++ b/docker/db-scripts/import_schema
@@ -4,6 +4,10 @@ if [ -z $1 ]; then
     echo "Must provide the database name, and name the .sql file <db name>_schema.sql"
     exit 1
 fi
+if [[ $1 =~ ^[0-9a-zA-Z\$_]+$  ]]; then
+    echo "Invalid string format for database: Must be alphnumeric."
+    exit 2
+fi
 
 # Pass in the filename as 2nd param, otherwise its name is assumed to match the
 # db-name and be suffixed "_schema.sql"
diff --git a/docker/db-scripts/show_indexes b/docker/db-scripts/show_indexes
--- a/docker/db-scripts/show_indexes
+++ b/docker/db-scripts/show_indexes
@@ -8,6 +8,14 @@ if [ -z $2 ]; then
     echo "Must provide the table name"
     exit 1
 fi
+if [[ $1 =~ ^[0-9a-zA-Z\$_]+$  ]]; then
+    echo "Invalid string format for database: Must be alphnumeric."
+    exit 2
+fi
+if [[ $2 =~ ^[0-9a-zA-Z\$_]+$  ]]; then
+    echo "Invalid string format for table name: Must be alphnumeric."
+    exit 2
+fi
 
 mysqlshow -u root -p$(echo $MYSQL_ROOT_PASSWORD) --keys $1 $2
 
diff --git a/docker/db-scripts/show_tables b/docker/db-scripts/show_tables
--- a/docker/db-scripts/show_tables
+++ b/docker/db-scripts/show_tables
@@ -4,6 +4,10 @@ if [ -z $1 ]; then
     echo "Must provide the database name"
     exit 1
 fi
+if [[ $1 =~ ^[0-9a-zA-Z\$_]+$  ]]; then
+    echo "Invalid string format for database: Must be alphnumeric."
+    exit 2
+fi
 
 mysql -D $1 -u root -p$(echo $MYSQL_ROOT_PASSWORD) -e "show tables;"
 
